import type { ArgNode } from "@airaga/parser/types/ast.js";

/**
 * @description The Engine class is responsible for rendering the AST (Abstract Syntax Tree)
 *              generated by the parser into actual DOM elements. It takes an ArgNode as input
 *              and recursively creates HTML elements based on the node's type, properties, content,
 *              and children. The resulting HTMLElement can then be appended to the document or used
 *              as needed in the application.
 * @example
 * ```javascript
 * const ast = {
 *   type: 'div',
 *   props: { class: 'container' },
 *   children: [
 *     { type: 'h1', content: 'Hello, World!' },
 *     { type: 'p', content: 'This is a paragraph.' }
 *   ]
 * };
 *
 * const element = Engine.renderer(ast);
 * document.body.appendChild(element);
 * ```
 */
export class Engine {
  /**
   * @description Renders an ArgNode into an HTMLElement. It creates an element based on the node's type,
   *              sets its attributes from the node's props, assigns text content if available, and recursively
   *              renders any child nodes. The resulting HTMLElement is returned for further use.
   * @param {ArgNode} node - The AST node to be rendered into an HTMLElement.
   * @returns {HTMLElement} The rendered HTMLElement corresponding to the input ArgNode.
   */
  public static renderer(node: ArgNode): HTMLElement {
    const element = document.createElement(node.type);

    if (node.props) {
      Object.entries(node.props).forEach(([key, value]) => {
        element.setAttribute(key, String(value));
      });
    }

    if (node.content) {
      element.textContent = node.content;
    }

    if (node.children) {
      node.children.forEach((child) =>
        element.appendChild(this.renderer(child)),
      );
    }

    return element;
  }
}
